ALTER TABLE hero_spell DROP FOREIGN KEY FK_HS_HERO;
ALTER TABLE hero_spell
ADD CONSTRAINT FK_HS_HERO
FOREIGN KEY (hero_id) REFERENCES hero (id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE hero_spell DROP FOREIGN KEY FK_HS_SPELL;
ALTER TABLE hero_spell
  ADD CONSTRAINT FK_HS_SPELL
FOREIGN KEY (spell_id) REFERENCES spell (id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE account_spell DROP FOREIGN KEY FK_AS_ACCOUNT;
ALTER TABLE account_spell
  ADD CONSTRAINT FK_AS_ACCOUNT
FOREIGN KEY (account_id) REFERENCES account (id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE account_spell DROP FOREIGN KEY FK_AS_SPELL;
ALTER TABLE account_spell
  ADD CONSTRAINT FK_AS_SPELL
FOREIGN KEY (spell_id) REFERENCES spell (id) ON DELETE CASCADE ON UPDATE CASCADE;

UPDATE spell SET id = 'SUCKER_PUNCH' WHERE id = '1';
UPDATE spell SET id = 'SELF_HEAL' WHERE id = '2';
UPDATE spell SET id = 'DAMAGED_HEAL' WHERE id = '3';
UPDATE spell SET id = 'DIVINE_COMFORT' WHERE id = '4';
UPDATE spell SET id = 'ELDRICH_PULL' WHERE id = '5';
UPDATE spell SET id = 'UPPERCUT' WHERE id = '6';
UPDATE spell SET id = 'SHOOT_THEM_ALL' WHERE id = '7';
UPDATE spell SET id = 'JUDGEMENT' WHERE id = '8';

ALTER TABLE spell DROP name;