INSERT INTO `brawl`.`hero` (`id`, `owner_id`, `name`) VALUES ('7', '1', 'WonderWoman');
INSERT INTO `brawl`.`hero` (`id`, `owner_id`, `name`) VALUES ('8', '2', 'Kevill');
INSERT INTO `brawl`.`hero` (`id`, `owner_id`, `name`) VALUES ('9', '2', 'Aizenberg');
INSERT INTO `brawl`.`hero` (`id`, `owner_id`, `name`) VALUES ('10', '2', 'Gadot');

UPDATE `brawl`.`hero_squad` SET `squad_id`='1' WHERE `hero_id`='5' and`squad_id`='3';
UPDATE `brawl`.`hero_squad` SET `squad_id`='1' WHERE `hero_id`='6' and`squad_id`='3';
INSERT INTO `brawl`.`hero_squad` (`hero_id`, `squad_id`) VALUES ('7', '1');
INSERT INTO `brawl`.`hero_squad` (`hero_id`, `squad_id`) VALUES ('8', '2');
INSERT INTO `brawl`.`hero_squad` (`hero_id`, `squad_id`) VALUES ('9', '2');
INSERT INTO `brawl`.`hero_squad` (`hero_id`, `squad_id`) VALUES ('10', '2');

DELETE FROM `brawl`.`squad` WHERE `id`='3';

INSERT INTO `brawl`.`hero_spell` (`hero_id`, `spell_id`) VALUES ('5', '7');
INSERT INTO `brawl`.`hero_spell` (`hero_id`, `spell_id`) VALUES ('5', '8');
INSERT INTO `brawl`.`hero_spell` (`hero_id`, `spell_id`) VALUES ('5', '1');
INSERT INTO `brawl`.`hero_spell` (`hero_id`, `spell_id`) VALUES ('5', '3');
INSERT INTO `brawl`.`hero_spell` (`hero_id`, `spell_id`) VALUES ('6', '7');
INSERT INTO `brawl`.`hero_spell` (`hero_id`, `spell_id`) VALUES ('6', '2');
INSERT INTO `brawl`.`hero_spell` (`hero_id`, `spell_id`) VALUES ('6', '5');
INSERT INTO `brawl`.`hero_spell` (`hero_id`, `spell_id`) VALUES ('6', '1');
INSERT INTO `brawl`.`hero_spell` (`hero_id`, `spell_id`) VALUES ('7', '4');
INSERT INTO `brawl`.`hero_spell` (`hero_id`, `spell_id`) VALUES ('7', '5');
INSERT INTO `brawl`.`hero_spell` (`hero_id`, `spell_id`) VALUES ('7', '6');
INSERT INTO `brawl`.`hero_spell` (`hero_id`, `spell_id`) VALUES ('7', '7');
INSERT INTO `brawl`.`hero_spell` (`hero_id`, `spell_id`) VALUES ('8', '1');
INSERT INTO `brawl`.`hero_spell` (`hero_id`, `spell_id`) VALUES ('8', '8');
INSERT INTO `brawl`.`hero_spell` (`hero_id`, `spell_id`) VALUES ('8', '3');
INSERT INTO `brawl`.`hero_spell` (`hero_id`, `spell_id`) VALUES ('8', '4');
INSERT INTO `brawl`.`hero_spell` (`hero_id`, `spell_id`) VALUES ('9', '3');
INSERT INTO `brawl`.`hero_spell` (`hero_id`, `spell_id`) VALUES ('9', '4');
INSERT INTO `brawl`.`hero_spell` (`hero_id`, `spell_id`) VALUES ('9', '5');
INSERT INTO `brawl`.`hero_spell` (`hero_id`, `spell_id`) VALUES ('9', '6');
INSERT INTO `brawl`.`hero_spell` (`hero_id`, `spell_id`) VALUES ('10', '7');
INSERT INTO `brawl`.`hero_spell` (`hero_id`, `spell_id`) VALUES ('10', '1');
INSERT INTO `brawl`.`hero_spell` (`hero_id`, `spell_id`) VALUES ('10', '2');
INSERT INTO `brawl`.`hero_spell` (`hero_id`, `spell_id`) VALUES ('10', '3');

INSERT INTO `brawl`.`hero_bodypart` (`hero_id`, `bodypart_id`) VALUES ('5', '1');
INSERT INTO `brawl`.`hero_bodypart` (`hero_id`, `bodypart_id`) VALUES ('5', '10');
INSERT INTO `brawl`.`hero_bodypart` (`hero_id`, `bodypart_id`) VALUES ('5', '4');
INSERT INTO `brawl`.`hero_bodypart` (`hero_id`, `bodypart_id`) VALUES ('5', '5');
INSERT INTO `brawl`.`hero_bodypart` (`hero_id`, `bodypart_id`) VALUES ('5', '6');
INSERT INTO `brawl`.`hero_bodypart` (`hero_id`, `bodypart_id`) VALUES ('5', '9');
INSERT INTO `brawl`.`hero_bodypart` (`hero_id`, `bodypart_id`) VALUES ('6', '1');
INSERT INTO `brawl`.`hero_bodypart` (`hero_id`, `bodypart_id`) VALUES ('6', '10');
INSERT INTO `brawl`.`hero_bodypart` (`hero_id`, `bodypart_id`) VALUES ('6', '4');
INSERT INTO `brawl`.`hero_bodypart` (`hero_id`, `bodypart_id`) VALUES ('6', '5');
INSERT INTO `brawl`.`hero_bodypart` (`hero_id`, `bodypart_id`) VALUES ('6', '6');
INSERT INTO `brawl`.`hero_bodypart` (`hero_id`, `bodypart_id`) VALUES ('6', '9');
INSERT INTO `brawl`.`hero_bodypart` (`hero_id`, `bodypart_id`) VALUES ('7', '1');
INSERT INTO `brawl`.`hero_bodypart` (`hero_id`, `bodypart_id`) VALUES ('7', '10');
INSERT INTO `brawl`.`hero_bodypart` (`hero_id`, `bodypart_id`) VALUES ('7', '4');
INSERT INTO `brawl`.`hero_bodypart` (`hero_id`, `bodypart_id`) VALUES ('7', '5');
INSERT INTO `brawl`.`hero_bodypart` (`hero_id`, `bodypart_id`) VALUES ('7', '6');
INSERT INTO `brawl`.`hero_bodypart` (`hero_id`, `bodypart_id`) VALUES ('7', '9');
INSERT INTO `brawl`.`hero_bodypart` (`hero_id`, `bodypart_id`) VALUES ('8', '1');
INSERT INTO `brawl`.`hero_bodypart` (`hero_id`, `bodypart_id`) VALUES ('8', '10');
INSERT INTO `brawl`.`hero_bodypart` (`hero_id`, `bodypart_id`) VALUES ('8', '4');
INSERT INTO `brawl`.`hero_bodypart` (`hero_id`, `bodypart_id`) VALUES ('8', '5');
INSERT INTO `brawl`.`hero_bodypart` (`hero_id`, `bodypart_id`) VALUES ('8', '6');
INSERT INTO `brawl`.`hero_bodypart` (`hero_id`, `bodypart_id`) VALUES ('8', '9');
INSERT INTO `brawl`.`hero_bodypart` (`hero_id`, `bodypart_id`) VALUES ('9', '1');
INSERT INTO `brawl`.`hero_bodypart` (`hero_id`, `bodypart_id`) VALUES ('9', '10');
INSERT INTO `brawl`.`hero_bodypart` (`hero_id`, `bodypart_id`) VALUES ('9', '4');
INSERT INTO `brawl`.`hero_bodypart` (`hero_id`, `bodypart_id`) VALUES ('9', '5');
INSERT INTO `brawl`.`hero_bodypart` (`hero_id`, `bodypart_id`) VALUES ('9', '6');
INSERT INTO `brawl`.`hero_bodypart` (`hero_id`, `bodypart_id`) VALUES ('9', '9');
INSERT INTO `brawl`.`hero_bodypart` (`hero_id`, `bodypart_id`) VALUES ('10', '1');
INSERT INTO `brawl`.`hero_bodypart` (`hero_id`, `bodypart_id`) VALUES ('10', '10');
INSERT INTO `brawl`.`hero_bodypart` (`hero_id`, `bodypart_id`) VALUES ('10', '4');
INSERT INTO `brawl`.`hero_bodypart` (`hero_id`, `bodypart_id`) VALUES ('10', '5');
INSERT INTO `brawl`.`hero_bodypart` (`hero_id`, `bodypart_id`) VALUES ('10', '6');
INSERT INTO `brawl`.`hero_bodypart` (`hero_id`, `bodypart_id`) VALUES ('10', '9');

INSERT INTO `brawl`.`hero_equipment` (`hero_id`, `equipment_id`) VALUES ('5', '1');
INSERT INTO `brawl`.`hero_equipment` (`hero_id`, `equipment_id`) VALUES ('5', '3');
INSERT INTO `brawl`.`hero_equipment` (`hero_id`, `equipment_id`) VALUES ('6', '1');
INSERT INTO `brawl`.`hero_equipment` (`hero_id`, `equipment_id`) VALUES ('6', '3');
INSERT INTO `brawl`.`hero_equipment` (`hero_id`, `equipment_id`) VALUES ('7', '1');
INSERT INTO `brawl`.`hero_equipment` (`hero_id`, `equipment_id`) VALUES ('7', '3');
INSERT INTO `brawl`.`hero_equipment` (`hero_id`, `equipment_id`) VALUES ('8', '1');
INSERT INTO `brawl`.`hero_equipment` (`hero_id`, `equipment_id`) VALUES ('8', '3');
INSERT INTO `brawl`.`hero_equipment` (`hero_id`, `equipment_id`) VALUES ('9', '1');
INSERT INTO `brawl`.`hero_equipment` (`hero_id`, `equipment_id`) VALUES ('9', '3');
INSERT INTO `brawl`.`hero_equipment` (`hero_id`, `equipment_id`) VALUES ('10', '1');
INSERT INTO `brawl`.`hero_equipment` (`hero_id`, `equipment_id`) VALUES ('10', '3');

INSERT INTO `brawl`.`account_spell` (`account_id`, `spell_id`) VALUES ('1', '6');
INSERT INTO `brawl`.`account_spell` (`account_id`, `spell_id`) VALUES ('1', '7');
INSERT INTO `brawl`.`account_spell` (`account_id`, `spell_id`) VALUES ('1', '8');
INSERT INTO `brawl`.`account_spell` (`account_id`, `spell_id`) VALUES ('2', '2');
INSERT INTO `brawl`.`account_spell` (`account_id`, `spell_id`) VALUES ('2', '4');
INSERT INTO `brawl`.`account_spell` (`account_id`, `spell_id`) VALUES ('2', '7');
INSERT INTO `brawl`.`account_spell` (`account_id`, `spell_id`) VALUES ('2', '8');
