version: '3'
services:
  db:
    container_name: db
    image: mysql:5.7.18
    ports:
      - $MYSQL_PORT:3306
    volumes:
      - $DB_VOLUME_LOCATION:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_HOST: localhost
    command:
      --character-set-server=utf8
      --collation-server=utf8_general_ci
  backend:
    container_name: backend
    image: adronex/clockworks
    ports:
      - $BACKEND_PORT:8080
      - $BACKEND_DEBUG_PORT:8787
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_PORT: 3306
      MYSQL_HOST: db # should be equal to database container name